site_name: CICD-to-GPU-Projects
repo_url: https://github.com/CarduCaldeira/
docs_dir: docs/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'indigo'
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'indigo'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - header.autohide
    - header.sticky
    - navigation.tracking
    - mode-toggle
  language: pt-BR

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [./]
  - exporter:
      logging:
        level: debug
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
          concurrency: 8
          stylesheets:
            - docs/assets/resources/stylesheets/pdf.scss
          covers:
            front: docs/assets/resources/templates/covers/front.html.j2
          aggregator:
            enabled: true
            output: site.pdf
            covers: front
  - macros

markdown_extensions:
  - pymdownx.tasklist  # List of tasks
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - markdown_include.include:
      base_path: ./
  - pymdownx.snippets:
      base_path: !relative $config_dir