name: ci

on:
  push:
      branches:
        - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: /root/.cache/uv
          key: ${{ runner.os }}-uv-cache-mount-${{ hashFiles('**/uv.lock') }}

      - name: Inject uv-cache-mount
        uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
        with:
          cache-source: /root/.cache/uv

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry
          cache-to: type=registry,mode=max
          tags: carloscaldeira/pytorch:2.5.1-cuda12.4-uv-runtime
