<<<<<<< HEAD
name: cd
=======
name: ci
>>>>>>> f9b44a9 (feature: add pipeline to build image docker)

on:
  push:
      branches:
        - main 
<<<<<<< HEAD
        - development
=======
>>>>>>> f9b44a9 (feature: add pipeline to build image docker)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Check out the repository
        uses: actions/checkout@v4
=======
>>>>>>> f9b44a9 (feature: add pipeline to build image docker)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

<<<<<<< HEAD
      - name: Cache for mount cache in Docker
        uses: actions/cache@v3
        id: cache
        with:
          path: root-cache-uv
          key: ${{ runner.os }}-uv-cache-mount-${{ hashFiles('uv.lock') }}

      - name: Inject uv-cache-mount
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0 
        with:
          cache-map: |
            {
              "root-cache-uv": "/root/.cache/uv"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

=======
      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: /root/.cache/uv
          key: ${{ runner.os }}-uv-cache-mount-${{ hashFiles('**/uv.lock') }}

      - name: Inject uv-cache-mount
        uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
        with:
          cache-source: /root/.cache/uv
>>>>>>> f9b44a9 (feature: add pipeline to build image docker)

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
<<<<<<< HEAD
          tags: carloscaldeira/pytorch:2.5.1-cuda12.4-uv-runtime
          push: true
=======
          cache-from: type=registry
          cache-to: type=registry,mode=max
          tags: carloscaldeira/pytorch:2.5.1-cuda12.4-uv-runtime
>>>>>>> f9b44a9 (feature: add pipeline to build image docker)
