name: cd

on:
  push:
      branches:
        - main 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - development
          - runtime

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache for mount cache in Docker
        uses: actions/cache@v3
        id: cache
        with:
          path: root-cache-uv
          key: ${{ runner.os }}-uv-cache-mount-${{ hashFiles('uv.lock') }}

      - name: Inject uv-cache-mount
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0 
        with:
          cache-map: |
            {
              "root-cache-uv": "/root/.cache/uv"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: ${{ matrix.target }}
          tags: carloscaldeira/pytorch:2.5.1-cuda12.4-uv-${{ matrix.target }}