name: Publish Docs

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements_docs.txt