name: Cancel specific deploy job on timeout

on:
  pull_request:
    branches:
      - main
jobs:
  timeout:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel specific deploy job if queued
        env:
          SLEEP_DURATION: ${{ vars.SLEEP_DURATION }}
          WORKFLOW_NAME: ${{ vars.WORKFLOW_NAME }}
          JOB_NAME: ${{ vars.JOB_NAME }}
        run: |
          sleep $SLEEP_DURATION
          
          JOB_ID=$(gh -R {owner}/{repo} run list -w $WORKFLOW_NAME -s queued --json jobs --jq ".[] | select(.name==\"$JOB_NAME\") | .databaseId" | head -n 1)
          
          if [ -n "$JOB_ID" ]; then
            echo "Canceling job: $JOB_NAME with ID: $JOB_ID"
            gh -R {owner}/{repo} run cancel $JOB_ID
          else
            echo "No queued job named $JOB_NAME found"
          fi